#!/bin/sh

# Gradle start up script for POSIX generated by Gradle.

# Important for running on Windows with non-ASCII characters in this directory.

app_path="${0}"

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}   # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)  app_path=$link ;; #(
      *)   app_path=$APP_HOME$link ;;
    esac
done

APP_HOME=$( cd "${APP_HOME:-.}" && pwd -P ) || exit

JAVA_HOME=$JAVA_HOME
JAVA_EXE=$JAVA_HOME/bin/java

if [ ! -x "$JAVA_EXE" ] ; then
    echo "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
    echo "Please set the JAVA_HOME variable in your environment to match the"
    echo "location of your Java installation."
    exit 1
fi

if [ -z "$CLASSPATH" ] ; then
    CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar
else
    CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar:$CLASSPATH
fi

exec "$JAVA_EXE" $DEFAULT_JVM_OPTS $JAVA_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
